README.md
package.json

I did see the previous PR #17 - but after reading some docs on submodules, this approach might be cleaner? No idea actually. Also wanted to add the INSTALL steps to the README.md
I am very interested in this project and will be happy to help with developer ergonomics or docs, etc

Add submodule init step & README install steps

---

src/bundle/createSES.js
src/bundle/hardenPrimordials.js
src/bundle/index.js
src/bundle/removeProperties.js
src/bundle/whitelist.js
test/test-freeze.js
test/test-nesting.js
test/test.js

This switches the way we freeze primordials to include the "anonmyous intrinsics", like `%MapIterator%` and `%GeneratorFunction%`. We must execute code to reach these, as they are not reachable by normal property/prototype lookup.

freeze primordials

---

.npmignore
package-lock.json
package.json
src/commonjs-index.js

This PR should make the typical package installation process for Node work smoothly with SES. Changes include:
* moving esm to be a regular dependency rather than a dev-dependency, so it gets installed automatically when SES is installed as an npm package
* creating a file that exports SES as a CommonJS module using `esm`
* changing package.json to point `main` to the CommonJS module
* adding an .npmignore so that we aren't installing more than we need to
1. Clone the SES repo and checkout branch `nodejs-compatible`
1. Inside the SES folder, run `npm pack` . This will create a tarball.
1. Unpack the tarball into its own directory. 
1. Create an empty Node.js project in another directory
1. Inside the new empty Node.js project, run `npm install ../package` where package is what was …

make using SES in Node.js easier

---

src/bundle/createSES.js
src/bundle/make-require.js
test/test-require.js

There's an esm-related name-mangling problem still pending, so this patch
can't use a simple lazy eval() yet. Instead, we use r.evaluate() from
outside, then pass the new Nat() function into makeRequire(). This forces us
to evaluate the function when creating the SES realm, even if nobody ever
calls require() with 'nat'. Once we figure out that problem, we can revert to
the simpler/lazier version.
refs #51

add require('nat') to the environment if requireMode:'allow'

---

package-lock.json
package.json
test/test-console.js

Upgrade to esm@3.2.5 to avoid a "console gets renamed by esm" problem, which
would otherwise break the new test.

test-console: test that SES.confine includes console.log too

---

src/bundle/createSES.js
src/bundle/make-require.js
test/test-nat.js
test/test-require.js

In the longer run, Nat will be removed from SES entirely, and a more generic
approach to require() will allow e.g. PlaygroundVat to provide it as a global
to imported code. But for now, changing this name to match the NPM package
name should let us start writing code that works in both modes.

remove Nat from global, use require('@agoric/nat') to get it

---

src/bundle/anonIntrinsics.js
src/bundle/whitelist.js

We were missing AsyncIteratorPrototype, which is the
prototype (getPrototypeOf) of AsyncGeneratorPrototype, which is
the (dot)prototype of AsyncGenerator. Our current deepFreeze follows both
sorts of links, so AsyncIteratorPrototype was being frozen, but the new
version (harden) doesn't follow getPrototypeOf, so it wouldn't have been
frozen there.
Also add AsyncIteratorPrototype to the whitelist so it will be retained.
refs #58

anonIntrinsics: add AsyncIteratorPrototype

---

.eslintignore
.eslintrc.js
package.json

adds demo and scripts to .eslintignore instead of having a different npm script command

standardize applied eslint rules

---

.circleci/config.yml

This PR adds configurations to the CircleCI config.yml to test versions 7, 8, 9, 10, and 11 of Node.js. However, CircleCI does not currently have an `allow_failure` mode, so if any tests fail, the whole process fails in CircleCI. We know that the test suite will fail on Node 7, 8, and 9, so for now, those jobs are commented out. When we do want to test those versions, we can uncomment those jobs on those branches. It's a bit hacky, but I think it's the only solution for now. 
Check that CircleCI is only running the jobs for Node.js version 10 and 11, and that everything passes.

Test Multiple Versions of Node

---

src/bundle/whitelist.js

This PR adds a line for `matchAll`. 
`Symbol.matchAll` is present in Chrome 73, and its presence without being on the whitelist or otherwise handled causes SES to error (see Issue #90). 
Closes #90

Add Symbol.matchAll to whitelist

---

docs/api.md

Tried evaluating the example in the docs and found it was missing a few calls, and replacing the `toString` of `Function.prototype` rather than `Object.prototype`.

Fixes to endowment safety example

---

demo/README.md
demo/index.html

This PR makes a change to the demo to pull in SES from unpkg.
Originally, the demo was using the SES file generated by rollup and committed to the repo. Then, when we started to have a policy of `gitignore`-ing the generated files, the demo [got a 404 for SES](https://github.com/Agoric/SES/issues/91#issuecomment-480127922), since the generated files were not built or present in the repo. This fixes that 404 error. 
I used a floating reference to SES. `https://unpkg.com/ses` will resolve to the latest version. This has the benefit of not having to remember to change the version number on each new release. However, I could also see the possibility of having a preference for the pinned version, e.g. `https://unpkg.com/ses@0.5.0/dist/ses.umd.js`

FIX: change SES script in demo to point to unpkg

---

src/bundle/createSES.js
src/bundle/make-console.js

See also: https://github.com/tc39/proposal-realms/pull/207
When the err.stack is undefined, Chrome will only display Uncaught undefined instead of the error message. This patch adds in the error message if the stack is not set so that there is a better diagnostic.

Fix "Uncaught undefined" in Chrome.

---

package.json
src/bundle/createSES.js
src/bundle/whitelist.js

This feature is used by the [@agoric/transform-bang](https://github.com/Agoric/transform-bang) transformer, and will also be used by the future `@agoric/transform-module`.
The transforms themselves are entirely implemented in realms-shim, so all we need to do is pass through the option.

options.transforms: forward to Realm.makeRootRealm

---

src/bundle/whitelist.js
test/test-removal.js

createSESRootRealm was preventing indirect eval from working, since realms-shim puts the `eval` definition in the globals.  The absence of `eval` from the whitelist meant that SES would happily remove the definition.
This may be handled differently in the future if we decide to put `eval` in the scopeTarget instead of the safeGlobal.
closes https://github.com/Agoric/realms-shim/issues/25

whitelist: allow realms-shim indirect eval

---

.circleci/config.yml

We're getting false failures from the nightly post-release test because the development version of SES is not uploaded to NPM.
This condition ensures we only test NPM releases after they've been uploaded.
There may be a better way to solve this.

test-post-release.js: don't test stale unpkg uploads

---

docs/source/draft-standalone-spec.rst

The bulleted list got smashed together. Perhaps this happened in the conversion from *.md to *.rst ? Where else may we have made this mistake? How can we avoid making it again?

Restore formatting that got dropped

---

src/bundle/removeProperties.js
src/bundle/whitelist.js
test/test-removal.js

Fixes #133 
It was an oversight not whitelisting `__proto__` when the whitelist was copied from the old SES into the modern one.

whitelist __proto__ because it is safe by SES rules

---

src/bundle/createSES.js
src/bundle/whitelist.js
test/test.js

This global `SES.harden` property is useful to allow code to harden objects when running under SES.
Specifically, I would like to use it in the HandledPromise implementation so that in non-SES environments hardening is stubbed out with an Object.freeze, and we do not have a dependency on an `@agoric/harden` module import to harden under SES (where the hardening behaviour is mandatory).
I can then do module code like:
```js
const harden = globalThis.SES && globalThis.SES.harden || Object.freeze;
```

createSES.js: create a global SES.harden

---

src/bundle/dataPropertiesToRepair.js

npm package `bluebird` and others create custom Error objects and expect to be able to set `MyError.prototype.toString`.

repair Error.prototype.toString

---

src/bundle/dataPropertiesToRepair.js

`readable-stream` (~39 mil downloads / week) creates subclasses of TypeError using function class inheritance
https://github.com/nodejs/readable-stream/blob/edd8c2d87c0f43f4f1d78407ac972fc193e45b40/errors-browser.js#L3
https://github.com/nodejs/readable-stream/blob/edd8c2d87c0f43f4f1d78407ac972fc193e45b40/errors-browser.js#L32-L33
cc @dckc

repair TypeError.prototype

---

docs/source/draft-standalone-spec.md

I took out `import.meta` too as it was on the same line; I don't know whether you want that in or out.

don't omit import()
